# Generated by Django 3.2 on 2022-04-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='category',
        ),
    ]
