# Generated by Django 3.2 on 2022-07-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20220721_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='description_paragraph1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='description_paragraph2',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='description_paragraph3',
        ),
    ]
