# Generated by Django 3.2 on 2022-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('PR', 'Personalisation Request'), ('BS', 'Bespoke / Sourcing Enquiry'), ('DE', 'Delivery'), ('ER', 'Exchange / Refund'), ('CO', 'Work With Us'), ('OT', 'Other')], default='OT', max_length=200),
        ),
    ]
