# Generated by Django 3.2 on 2022-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_query_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
