# Generated by Django 3.2 on 2022-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
