# Generated by Django 3.2 on 2022-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220411_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image1_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
