# Generated by Django 3.2 on 2022-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220413_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multibuy_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
