# Generated by Django 3.2 on 2022-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220419_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
