# Generated by Django 3.2 on 2022-04-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
    ]
