# Generated by Django 3.2 on 2022-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220427_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multibuy_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
