# Generated by Django 3.2 on 2022-05-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_multibuy_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
