# Generated by Django 3.2 on 2022-05-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
    ]
