# Generated by Django 3.2 on 2022-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_category_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_paragraph1',
        ),
        migrations.AddField(
            model_name='product',
            name='description_paragraph2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_paragraph3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
